### ISSUE TITLE
Pelo menos tres tipos de Layouts;

### ISSUE THREAD

**Issue by FelipeGms** [FelipeGms/droid_doctor_app#8]
-> Table Layout em app/src/main/res/layout/activity_history_patient.xml; OK
-> Linear Layout e ScrollView em app/src/main/res/layout/activity_menu.xml;OK

**Comment by FelipeGms** [comment]
Pelo que vi esse requisito foi concluído.

**Comment by viniciusalonso** [comment]
@FelipeGms :+1:
